# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "1007",
  "password": "1007",
  "checked": true
}
###
POST http://localhost:8080/api/cookielogin
Cookie:number=a0246a6d164540eeb6d99354538b7297d185b421521073284c3fdd1714f4d4858155f5452a8d040a905d6058f0ee7cf2

###
GET http://localhost:8080/pp
Authorization:bc9b8b30515c3e3e34e376bf5487a33c165003b9701030d420ee41f14e4858b2959c3be446d36a3726af32cfe8f33426

###
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

{
  "number": "1","password": "aa"
}
###
