# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
### Send a form with the text and file fields
### Send a form with the text and file fields
POST http://localhost:8080/test/uploadtest
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="number"

1007
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.json"

< post.http
--WebAppBoundary--

###